### ISSUE TITLE
Review refactored ndrop code

### ISSUE THREAD

**Issue by mattldawson** [NCAR/ACOM-SE-tasks#33]
See
https://github.com/fvitt/CAM/tree/carma_mam_classes/src

The abstract and extended class code files are:
 chemistry/aerosol/*aerosol_*_mod.F90

**Comment by andrewgettelman** [comment]
Thanks. As a non-SE, that doesn't make a whole lot of sense to me yet. I think I understand where this is headed, but will be interested to see how it intersects the science code.
