### ISSUE TITLE
Add CAM regression tests for CARMA models

### ISSUE THREAD

**Issue by fvitt** [NCAR/ACOM-SE-tasks#5]

**Comment by manderberg** [comment]
Files for CAM regression tests for all CARMA models except cirrus, cirrus_dust, test_detrain and mixed_sulfate pushed to branch cam-carma_tests on my fork on cam_development: a new testlist_cam.xml and new directories for each model in <CAM root>/cime_config/testdefs/testmodes_dirs/cam containing the namelist files and shell_commands file specific to each model. A pull request (#505) has been initiated.

**Comment by manderberg** [comment]
Regression tests for 13 CARMA models have been added to CAM regression tests. CAM tag is cam6_3_0505. 
CAM issue #420 has not yet closed by this becasue not all models are yet represented in the tests.
